### ISSUE TITLE
Webpack cache busting not fully implemented

### ISSUE THREAD

**Issue by DBosley** [AngularClass/angular-starter#1703] opened 2017-04-27 16:31 UTC
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
If you're using lazy loading with angular modules these all generate chunk files in the webpack output. Webpack creates a manifest of chunk references to file names. By default, this manifest is loaded into the first defined webpack entry point's output file. When the manifest changes, however, the chunkhash for that specific output file isn't guaranteed to change. In the current project, 'Polyfills' is the first entry point. This file very rarely changes and the chunkhash for it will always be the same. This means the manifest never gets updated and will contain old file references when loaded from cache.

* **What is the expected behavior?**
the webpack manifest should be extracted from the output and injected into the index html

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Webpack documentation on how to implement proper chunkhash caching:
https://webpack.js.org/guides/caching/

**Comment by jkreileder** [comment] 2017-04-28 19:47
Like this? https://github.com/jkreileder/angular-lightning-webpack-starter/commit/91ec5b81b64ec58c04094d1ac5cf82a823d320d5
Will send a pull request if there's interest.

**Comment by colinskow** [comment] 2017-05-01 08:39
It looks like our output generates MD5 hashes that are embedded in the names of the source files. I thought this was the primary mechanism to ensure correct caching.

This sounds like a valuable pull request, but I would like to better understand the problem we are trying to solve.

**Comment by jkreileder** [comment] 2017-05-01 12:28
Yes, but you want to keep cache busting as minimal as possible. Currently each change to the application code also invalidates the polyfills bundle:

Original:
```
0.420d6c76fa8938a2547f.chunk.js
1.cc39a588cf9a6aab422d.chunk.js
2.cd20cdf22c5651d965f6.chunk.js
5.4c102ffef891d7aede1c.chunk.js
6.cea5ea445288c79e42e4.chunk.js
main.0a01f4183ca940373589.bundle.js
polyfills.8258808d5bf4b9758918.bundle.js
vendor.a2ff3b67548bea4e88b8.bundle.js
```
Now change, for example, 'Hello from Barrel' to 'Hi from Barrel' in src/app/+barrel/barrel.component.ts
Result:
```
0.420d6c76fa8938a2547f.chunk.js
1.da087417ad3cced709d8.chunk.js
2.cd20cdf22c5651d965f6.chunk.js
5.4c102ffef891d7aede1c.chunk.js
6.cea5ea445288c79e42e4.chunk.js
main.0a01f4183ca940373589.bundle.js
polyfills.13d204d91050cce84540.bundle.js
vendor.a2ff3b67548bea4e88b8.bundle.js
```
The hash of chunk 1 has changed, this is expected because it contains the corresponding code.
But the hash of the polyfills bundles has changed too, although there was no change there! That's because the runtime code, which contains references to the chunk names (which changed), is included in the polyfills bundle.

Now the same with extracted manifest:
```
0.5499456cca58c08366a0.chunk.js
1.d7e5a7938c9f4248bbdb.chunk.js
2.cd6bff9a11b4248469ff.chunk.js
6.a7ba61bceaa6b30b0453.chunk.js
7.78639e0f1e44743f9840.chunk.js
main.03f6915b39567582fe3d.bundle.js
manifest.83fcaa69daecd0504afd.bundle.js
polyfills.7118dbd4c5b135632fc7.bundle.js
vendor.0155986f7d6517ebb116.bundle.js
```
And after changing src/app/+barrel/barrel.component.ts:
```
0.5499456cca58c08366a0.chunk.js
1.3dd02aa0e8e4a218f01d.chunk.js
2.cd6bff9a11b4248469ff.chunk.js
6.a7ba61bceaa6b30b0453.chunk.js
7.78639e0f1e44743f9840.chunk.js
main.03f6915b39567582fe3d.bundle.js
manifest.85626f9b3700a3359fe3.bundle.js
polyfills.7118dbd4c5b135632fc7.bundle.js
vendor.0155986f7d6517ebb116.bundle.js
```
Only chunk 1 and the manifest bundle have new hashes! The hash of the much larger polyfills bundle didn't change. (https://github.com/jkreileder/angular-lightning-webpack-starter/commit/91ec5b81b64ec58c04094d1ac5cf82a823d320d5 inlines the manifest bundle in index.html instead of keeping it separately.)
In terms of caching this means (with inlining): 1 file with 1kB has been invalidated instead of 2 with 100kB. 

The other case mentioned by @DBosley (manifest changed but not the hash of the bundle containing it) is something I can't reproduce.

On the other hand, this repo does have more caching issues: Copying of assets to dist, then using those assets without hashes in the filename. It would be better to require all needed assets and let webpack copy them to dist implicitly. And also use html-loader instead of raw-loader for *.html.
https://github.com/jkreileder/angular-lightning-webpack-starter/commit/e2fef47c915bb625ed6a66ab460b4ad3bba9afbd is a partial fix for this: It fixes the things I need in my fork but not the generated image URLs in index.html and the WebApp manifest.json (unrelated to the manifest we're talking about above).

**Comment by DBosley** [comment] 2017-05-01 15:08
It's interesting that you @jkreileder couldn't repro the issue I saw. I'm working in a project that uses this as a base, but has been changed significantly. I'll have see if I can find the reason for the issue I'm seeing. Extracting the manifest did fix my caching issues, however. Also as the webpack 2 docs state, it's the correct way to do cachebusting.

**Comment by colinskow** [comment] 2017-05-02 00:42
@jkreileder thank you very much for your explanation. A pull request would be very much appreciated.

**Comment by karolmie1** [comment] 2017-07-28 10:21
There is an interesting article about cache busting here: https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31

@jkreileder Does current setup addresses problems raised in this article?

**Comment by gdi2290** [comment] 2017-09-02 09:27
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue

**Closed by gdi2290** 2017-09-02 09:27 UTC
