### ISSUE TITLE
[Feat] Static template compilation, Web Workers, Service Workers and sw-precache

### ISSUE THREAD

**Issue by luchillo17** [AngularClass/angular-starter#728] opened 2016-06-24 14:26 UTC
- **I'm submitting a ...**
  [x] feature request
- **Do you want to request a _feature_ or report a _bug_?**
  A feature
- **What is the current behavior?**
  There's no current support for [Static Template Compilation](http://teropa.info/blog/2016/05/19/things-that-excite-me-about-angular-2.html#static-template-compilation) nor [Web Workers](http://teropa.info/blog/2016/05/19/things-that-excite-me-about-angular-2.html#web-worker-support) nor [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)
- **What is the expected behavior?**
  Have support for those 3 technologies in the app.
- **What is the motivation / use case for changing the behavior?**
  - Static template compilation: Speed up the render process and performance as well as lowering the size of the bundles.
  - Web Workers: Offloading resource intensive operations to a new thread thus making better use of multicore cpus (today even mobile have multicore).
  - Service workers: Mainly to support offline applications using libs like [sw-precache](https://github.com/GoogleChrome/sw-precache) or [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox), but also to support background sync and push notifications.  
- **Other information**
  Here are some links about those subjects:
  - [Static Template Compilation](http://teropa.info/blog/2016/05/19/things-that-excite-me-about-angular-2.html#static-template-compilation)
  - [Web Workers](http://teropa.info/blog/2016/05/19/things-that-excite-me-about-angular-2.html#web-worker-support)
  - [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)
  - [The difference between Service Workers, Web Workers and WebSockets](https://aarontgrogg.com/blog/2015/07/20/the-difference-between-service-workers-web-workers-and-websockets)

Aditionally i'm working on the sw and sw-precache feature myself so i can provide some help in that field.

**Comment by Luchillo** [comment] 2016-06-24 17:55
I've been digging in how to integrate with webpack and so far i have seen 2 plugins that takes care of that:
- [Offline plugin](https://github.com/NekR/offline-plugin)
- [sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin)

So far it seems the Offline plugin is better since it states that it fallbacks to AppCache if service worker isn't supported in the browser, further testing and analysis required.

**Comment by Luchillo** [comment] 2016-06-24 20:37
After analysing the current support i take for granted that the best tool is Offline plugin since it allows to use a fallback to AppCache, the browsers related are Safari (partial support) and Edge (currently only available from development builds).

Resource (support):  https://jakearchibald.github.io/isserviceworkerready

**Comment by Luchillo** [comment] 2016-06-24 22:29
After a bit more testing i still think the `Offline plugin` is the way to go, it works excelent to generate both the service worker for offline support and the cache manifest for as fallback, as well as caching the app.

Meanwhile the `sw-precache-webpack-plugin` doesn't offer any fallback without support for service worker, it caches fine when in supported browsers, however docs are a bit outdated comparing to the code, and there's some weird behaviour where in production the service worker just generates 1 cache for each file instead of putting all files in the same cache, which i think is due to the `WebpackMd5Hash` plugin, idk if it's expected behaviour or a bug.

Lastly the `sw-precache-webpack-plugin` will not work with dev server as the generated service worker doesn't get served by the `webpack-dev-server`.

**Comment by gdi2290** [comment] 2016-06-27 21:23
ya, eventually these will all be added

**Comment by Luchillo** [comment] 2016-06-27 22:05
I already did add precache with webworkers and fallback to cache.manifest using the `Offline Plugin`, want me to make a PR?

Although people will need to be aware that Service Workers enforces https.

**Comment by Luchillo** [comment] 2016-06-27 22:10
Also have a `manifest.json` for Progressive Web Apps, could be a great addition.

**Comment by HipsterZipster** [comment] 2016-07-28 23:17
@Luchillo I'd love to see your webworker / cache.manifest integration. Please PR! 👍

**Comment by Luchillo** [comment] 2016-07-29 13:00
Gimme a week or so to put my repo on sync with the latest changes in this one.

**Comment by NekR** [comment] 2016-08-14 17:04
Hey, feel free to contact me if you need any help with `offline-plugin` integration :-)

**Comment by Luchillo** [comment] 2016-08-14 21:42
I've had mine working with that plugin for a month or so, but since i started my repo not as a clone but as a different project that after i merged this one, i think i shouldn't make a pull request with all the changes i've made, so i practically need to clone this and put it to work again.

**Comment by NekR** [comment] 2016-08-15 11:49
Okay, I think I may submit a PR later this week.

**Comment by talmog** [comment] 2017-02-06 20:14
Any updates? How can one create a progressive web app with this project?

**Closed** 2017-09-02 10:01 UTC

**Comment by nirajrajgor** [comment] 2017-09-26 19:50
Why there isn't any update for progressive web app on this project?? Did someone tried it?
