### ISSUE TITLE
How to load a 3rd party js file

### ISSUE THREAD

**Issue by AnotherStop** [AngularClass/angular-starter#570] opened 2016-05-07 15:44 UTC
I'm going to import a 3rd party js file in one of my angualr2 component.

```
import '../../../../js/d3gauge.js';
export class MemMonComponent {
    createMemGauge() {
        new drawGauge(this.opt);  //drawGauge() is a function inside d3gauge.js
    }
}
```

And, in the `custom-typings.d.ts` file, I added `declare var drawGauge: any;` and run `typings install`. 

But when I start the angular2 app, it still complains `ReferenceError: drawGauge is not defined`. could you point out whether there's something wrong? Thanks.

**Update:** after adding `<script src="./js/d3gauge.js"></script>` to `index.html, it works. But in this case, this js file will load for each component. How can I config webpack to load this js file only for certain components?

**Comment by doxiaodong** [comment] 2016-05-30 08:28
In my blog,  I use `emojione` as flow:
1. https://github.com/doxiaodong/darlin-angular2/blob/develop/src/app/base/emojione/emojione.d.ts
2. https://github.com/doxiaodong/darlin-angular2/blob/develop/src/app/base/marked/marked.component.ts

Good luck for you!

**Comment by reach4thelasers** [comment] 2016-07-09 23:05
I've got this question too - and I don't understand the given answer

**Comment by MurhafSousli** [comment] 2016-07-10 05:54
Don't add the script in index.html, use `require` instead of import:
Like this:
```
var drawGauge = require('../../../../js/d3gauge.js');

export class MemMonComponent {
    foo;
    createMemGauge() {
        this.foo = new drawGauge(this.opt);  //drawGauge() is a function inside d3gauge.js
    }
}
```

**Comment by lthh89vt** [comment] 2016-07-25 00:26
I'm having a similar issue,
I've tried require and it loads the script as soon as I run the app.
Is there a way to load it only for certain components.

thanks.

**Comment by srkkhan** [comment] 2016-09-27 12:36
any answer regarding this issue???

**Comment by lhammond** [comment] 2016-10-10 17:04
+1

**Comment by gilhanan** [comment] 2016-11-15 22:03
+1

**Comment by j-nord** [comment] 2016-11-20 17:38
+1

**Comment by camccar** [comment] 2016-11-28 04:10
+1

**Comment by itoufo** [comment] 2016-12-21 08:16
+1

**Comment by YagoLopez** [comment] 2016-12-21 18:14
It seems to be another wrong decision of the angular team, and not the first.

I had a library of components developed following the oficial angular documentation based on SystemJs. It used "import javascript_file.js" to load external javascript files and worked. Tried to port to new webpack version and it doesnt work at all. Also, the size of the app loaded by the browser went from 2.7 MB to 3.3.

The last news I have are the new version jumps from 2 to 4. Angular project it's a chaos that seems to have lost the north. It is bloated and over engineering. I'm going to change to React.

**Comment by messerbill** [comment] 2017-01-28 22:25
it really seems that the angular2 team does not care about existing implementations using their framework. In my opinion Angular2 will be great one day but actually it is nearly unusable. Not at least because of the 3rd party libraries. I know, this is not their fault at all but they are changing their framework really often and they do not update the docs in time. Last week i did an update for several angular2 tools and nothing worked until i downgraded it again. 
SystemJS produces a lot of errors at my place while webpack seems to work as expected....mostly. 

But to be fair: The angular2 developers clearly say that this is still a very early version and its still beta. I think when they release the first stable version those errors will vanish....hopefully.

**Comment by YagoLopez** [comment] 2017-02-02 22:36
After a lot of investigation i managed to use webpack and systemjs at the same time. In my very personal opinion recompile each time with webpack during development time is clearly overkill. You should at least have the chance of using both and be able to switch without problems, but at first instance they are incompatible. Webpack sould be used for production.

@messerbill It seems the latest version of typescript enable to include external libraries easier not forcing you to declare types so strictly but then you have to manage the way of load them as webpack plugins.  Also my version of webstorm throws errors with the latest typescript. Im trapped lol.

Typescript and Web components are good idea but so many moving parts and so much bloated code.... For example, using angular-cli you end having aaaaall testing frameworks duplicated as angular dependencies and angular-cli dependencies (jasmine, protractor, karma, selenium webdriver). May be npm is the culprit. It is needed more stability and clear guides. Supposedly Angular 2 have been ended beta phase and have been released as stable version.

You can take a look to the code at https://yagolopez.github.io/material-light/. It is a material desing library. May be you can find it useful. Greetings.

**Comment by YagoLopez** [comment] 2017-02-02 22:41
After a lot of investigation i managed to use webpack and systemjs at the same time. In my very personal opinion recompile each time with webpack during development time is clearly overkill. You should at least have the chance of using both and be able to switch without problems, but at first instance they are incompatible. Webpack sould be used for production.

@messerbill It seems the latest version of typescript enable to include external libraries easier not forcing you to declare types so strictly but then you have to manage the way of load them as webpack plugins.  Also my version of webstorm throws errors with the latest typescript. Im trapped lol.

Typescript and Web components are good idea but so many moving parts and so much bloated code.... For example, using angular-cli you end having aaaaall testing frameworks duplicated as angular dependencies and angular-cli dependencies (jasmine, protractor, karma, selenium webdriver). May be npm is the culprit. It is needed more stability and clear guides. Supposedly Angular 2 have been ended beta phase and have been released as stable version.

You can take a look to the code at [After a lot of investigation i managed to use webpack and systemjs at the same time. In my very personal opinion recompile each time with webpack during development time is clearly overkill. You should at least have the chance of using both and be able to switch without problems, but at first instance they are incompatible. Webpack sould be used for production.

@messerbill It seems the latest version of typescript enable to include external libraries easier not forcing you to declare types so strictly but then you have to manage the way of load them as webpack plugins.  Also my version of webstorm throws errors with the latest typescript. Im trapped lol.

Typescript and Web components are good idea but so many moving parts and so much bloated code.... For example, using angular-cli you end having aaaaall testing frameworks duplicated as angular dependencies and angular-cli dependencies (jasmine, protractor, karma, selenium webdriver). May be npm is the culprit. It is needed more stability and clear guides. Supposedly Angular 2 have been ended beta phase and have been released as stable version.

You can take a look to the code at https://yagolopez.github.io/material-light/. It is a material desing library. May be you can find it useful. Greetings.

**Comment by manzer001** [comment] 2017-06-14 18:28
I am using angular-cli, want to use external js library d3gauge.js in my component. How to use it ?

**Comment by Codefans-fan** [comment] 2017-06-26 05:58
@manzer001 
for angular-cli you can add js file in config file see 'scripts' ;
`{
    "project": {
    
    },
    "apps": [
        {
            "root": "",
            "outDir": "",
            "assets": [
                "content",
                "i18n",
                "favicon.ico"
            ],
            "index": "index.html",
            "main": "app/app.main.ts",
            "polyfills": "app/polyfills.ts",
            "test": "",
            "tsconfig": "../../../tsconfig.json",
            "mobile": false,
            "styles": [
                "content/scss/vendor.scss",
                "content/scss/global.scss"
            ],
            "scripts": [
                "./vendor/jqwidgets-framework/scripts/jquery-1.11.1.min.js",
                "./vendor/jqwidgets-framework/jqwidgets/jqx-all.js"
            ]
        }
    ],
    "addons": [],
    "packages": [],
    "e2e": {
        "protractor": {
            "config": "src/test/javascript/protractor.conf.js"
        }
    },
    "lint": [
        {
            "project": "../../../tsconfig.json"
        },
        {
            "project": "../../../tsconfig-aot.json"
        }
    ],
    "test": {
        "karma": {
            "config": "src/test/javascript/karma.conf.js"
        }
    },
    "defaults": {
        "styleExt": "scss",
        "prefixInterfaces": false,
        "inline": {
            "style": true,
            "template": false
        },
        "spec": {
            "component": false,
            "directive": false,
            "pipe": false,
            "service": false
        }
    }
}
`

**Comment by YagoLopez** [comment] 2017-06-26 11:05
A sugerence:

try to use 

`require ('../../../../js/d3gauge.js')`

With or without  ".js" extension, I dont remember exactly.

**Comment by Hulva** [comment] 2017-08-02 15:23
I‘m doing it [that way](https://github.com/Hulva/AngularDemos/blob/master/about-using-thirdparty-lib/README.md), hope that would help.

**Comment by gdi2290** [comment] 2017-09-02 09:32
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue

**Closed by gdi2290** 2017-09-02 09:32 UTC
Labels: question

**Comment by tuannn0107** [comment] 2017-09-12 08:54
I have issue that:
- i put my .js file into assets folder.
- i config at angular-cli.json

But when i routing from one component to another, the .js file did not load. However, i refreshed page (F5) and now the .js file is loaded.

Could someone can explain to me why? It so inconvenience for me.

**Comment by keivankashani** [comment] 2017-10-15 08:15
You can Import js locally to ts file like this : import '../../../scripts/custom.js';

then declare method name in custom.js that you want to use like this 👍 
declare var fAlert;
then in a place like ngOnInit directly use this method

fAlert();

**Comment by BatcherX** [comment] 2017-10-17 17:47
@keivankashani  As i remember you cant use declare in js .

**Comment by KhanHamidkhan** [comment] 2017-11-10 03:54
@keivankashani  Thank you so much it helped me  I have been trying for days but it worked now thank you

**Comment by aaron170** [comment] 2017-11-14 09:24
@keivankashani Your solution is good ... it works but the problem is that while we build the code and run then we get a ReferenceError. Also that refreshes the page twice while loading. If anyone has faced this issued then please send some solution.
here is the error attached.
![error](https://user-images.githubusercontent.com/19680243/32772403-c0d3e294-c94b-11e7-9e2c-cd30b27ad72e.jpg)

**Comment by YagoLopez** [comment] 2017-11-14 09:48
A couple of ideas:

- Try to load the javascript file in index.html using <script> tag (old Way)

- Use require("relative-path-to-js-file")

Good luck

El 14 nov. 2017 10:25 a. m., "Aaron Macwan" <notifications@github.com>
escribió:

@keivankashani <https://github.com/keivankashani> Your solution is good ...
it works but the problem is that while we build the code and run then we
get a ReferenceError. Also that refreshes the page twice while loading. If
anyone has faced this issued then please send some solution.
here is the error attached.
[image: error]
<https://user-images.githubusercontent.com/19680243/32772403-c0d3e294-c94b-11e7-9e2c-cd30b27ad72e.jpg>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gdi2290/angular-starter/issues/570#issuecomment-344195779>,
or mute the thread

**Comment by kavithamadhavaraj** [comment] 2018-06-07 13:11
`Angular CLI: 6.0.8
Node: 10.4.0
OS: linux x64
Angular: 6.0.4
`

For me, just including the scripts in the index.html (usual way as mentioned by @YagoLopez ) worked.
